package cookieclicker;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Elias
 */
public class CookieClickerGUI extends javax.swing.JFrame {

    /**
     * Creates new form CookieClickerGUI
     */
    public CookieClickerGUI() {
        initComponents();
        scaleCookie();
    }
    
    public void scaleCookie() {
        ImageIcon cookieIcon = new ImageIcon("src/cookieclicker/images/PerfectCookie.png");
        Image image = cookieIcon.getImage();
        Image newImage = image.getScaledInstance(cookieButton.getWidth(), cookieButton.getHeight(), Image.SCALE_SMOOTH);
        cookieButton.setIcon(new ImageIcon(newImage));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        cookieButton = new javax.swing.JLabel();
        cookieLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cookieCountText = new javax.swing.JLabel();
        cookieCount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 700));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        bg.add(cookieButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 340, 340));

        cookieLabel.setFont(new java.awt.Font("Samurai Blast", 0, 48)); // NOI18N
        cookieLabel.setText("GALLETAS");
        bg.add(cookieLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 250, 100));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setAlignmentX(1.0F);
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 340, 20));

        cookieCountText.setFont(new java.awt.Font("Dubai", 1, 28)); // NOI18N
        cookieCountText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cookieCountText.setText("MIL");
        bg.add(cookieCountText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 210, 40));

        cookieCount.setFont(new java.awt.Font("Dubai", 1, 48)); // NOI18N
        cookieCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cookieCount.setText("0");
        bg.add(cookieCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 210, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 1108, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CookieClickerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CookieClickerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CookieClickerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CookieClickerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CookieClickerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel cookieButton;
    private javax.swing.JLabel cookieCount;
    private javax.swing.JLabel cookieCountText;
    private javax.swing.JLabel cookieLabel;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
